#pragma once

enum HorizontalFacing
{
	FIRST_HORIZONTAL_FACING,
	LEFT = FIRST_HORIZONTAL_FACING,
	RIGHT,
	LAST_HORIZONTAL_FACING
};

enum VerticalFacing
{
	FIRST_VERTICAL_FACING,
	UP = FIRST_VERTICAL_FACING,
	DOWN,
	HORIZONTAL,
	LAST_VERTICAL_FACING
};